# name: workflow

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - "*"

# jobs:
#   integration:
#     name: Continuous Integration
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out repo code
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.x"

#       - name: Install Dependencies
#         run: |
#           make install

#       - name: Format code
#         run: |
#           make format

#   deployment:
#     name: Continuous Deployment
#     runs-on: ubuntu-latest
#     needs: integration
#     if: |
#       github.event_name == 'push' &&
#       github.event.workflow_run.conclusion == 'success'

#     steps:
#       - name: Check out repo code
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t jaweed2022/cost:latest .
#           docker push jaweed2022/cost:latest




name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          make install

      - name: Format code
        run: |
          make format

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jaweed2022
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t jaweed2022/cost:latest .
          docker push jaweed2022/cost:latest
